# Generated by Django 4.1.5 on 2023-01-03 11:17

from django.db import migrations, models
import django.db.models.deletion
import registry.models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.CharField(default=registry.models.uuid, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='license',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='id',
            field=models.CharField(default=registry.models.uuid, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='license',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='id',
            field=models.CharField(default=registry.models.uuid, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='ror',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='ROR Id'),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.CharField(default=registry.models.uuid, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='orcid',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='ORCID Id'),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.CharField(default=registry.models.uuid, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('STUDY_DESIGN', 'Study Design'), ('MATERIAL', 'Material'), ('TEST_METHOD', 'Test method'), ('DATA', 'Data')], max_length=100)),
                ('link', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('contributors', models.ManyToManyField(blank=True, related_name='resources', to='registry.person')),
                ('groups', models.ManyToManyField(blank=True, related_name='resources', to='registry.group')),
                ('license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='registry.license')),
            ],
            options={
                'ordering': ['name', 'kind'],
            },
        ),
    ]
