# Generated by Django 4.1.5 on 2023-02-07 09:46

from django.db import migrations, models
import django.db.models.deletion
import registry.models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_organisation_short_name_alter_organisation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='kind',
            field=models.CharField(choices=[('MATERIAL', 'Material'), ('TEST_METHOD', 'Test method'), ('DATA', 'Data')], max_length=100),
        ),
        migrations.AlterField(
            model_name='resource',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='registry.license'),
        ),
        migrations.CreateModel(
            name='StudyDesign',
            fields=[
                ('id', models.CharField(default=registry.models.uuid, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('contributors', models.ManyToManyField(blank=True, related_name='study_designs', to='registry.person')),
                ('groups', models.ManyToManyField(blank=True, related_name='study_designs', to='registry.group')),
                ('license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='study_designs', to='registry.license')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
