# Generated by Django 4.1.5 on 2023-02-20 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_alter_resource_kind_alter_resource_license_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='link',
            new_name='data_link',
        ),
    ]
