# Generated by Django 4.1.5 on 2023-02-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_rename_link_resource_data_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='data_link',
            field=models.URLField(blank=True, help_text='Link to data (e.g. Zenodo, Figshare, etc.)', null=True),
        ),
    ]
