# Generated by Django 4.1.5 on 2023-02-20 10:02

from django.db import migrations, models
import django.db.models.deletion
import registry.models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_alter_resource_data_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonRole',
            fields=[
                ('id', models.CharField(default=registry.models.uuid, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='resource',
            name='contributors',
        ),
        migrations.AddField(
            model_name='resource',
            name='data_file',
            field=models.FileField(blank=True, help_text='File containing data. In case of multiple files, please upload a zip file.', null=True, upload_to='resources/'),
        ),
        migrations.CreateModel(
            name='ResourceContributor',
            fields=[
                ('id', models.CharField(default=registry.models.uuid, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributes_to_resources', to='registry.person')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='registry.resource')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.personrole')),
            ],
            options={
                'ordering': ['resource__name', 'role__name'],
            },
        ),
    ]
