# Generated by Django 4.1.7 on 2023-02-20 10:13

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0007_personrole_remove_resource_contributors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='country',
            field=django_countries.fields.CountryField(default='', max_length=2),
            preserve_default=False,
        ),
    ]
