# Generated by Django 4.1.7 on 2023-02-20 13:33

from django.db import migrations, models
import django.db.models.deletion
import registry.models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0008_organisation_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceStatus',
            fields=[
                ('id', models.CharField(default=registry.models.uuid, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='resourcecontributor',
            unique_together={('resource', 'person', 'role')},
        ),
        migrations.AddField(
            model_name='resource',
            name='status',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='registry.resourcestatus'),
            preserve_default=False,
        ),
    ]
