# Generated by Django 4.1.7 on 2023-02-20 15:13

from django.db import migrations, models
import django.db.models.deletion
import registry.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('registry', '0010_alter_resourcestatus_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.CharField(default=registry.models.uuid, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributes_to_resources', to='registry.person')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.personrole')),
            ],
            options={
                'ordering': ['role__name', 'person__user__last_name', 'person__user__first_name'],
            },
        ),
        migrations.RemoveField(
            model_name='studydesign',
            name='contributors',
        ),
        migrations.DeleteModel(
            name='ResourceContributor',
        ),
        migrations.AddIndex(
            model_name='contributor',
            index=models.Index(fields=['content_type', 'object_id'], name='registry_co_content_256038_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contributor',
            unique_together={('person', 'role')},
        ),
    ]
