# Generated by Django 4.1.7 on 2023-02-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0011_contributor_remove_studydesign_contributors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='object_id',
            field=models.CharField(max_length=12),
        ),
    ]
