# Generated by Django 4.1.7 on 2023-02-20 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('registry', '0012_alter_contributor_object_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contributor',
            unique_together={('content_type', 'object_id', 'person', 'role')},
        ),
    ]
