# Generated by Django 4.1.7 on 2023-02-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0014_alter_resource_groups_alter_resource_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studydesign',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='study_designs', to='registry.group', verbose_name='Use cases'),
        ),
    ]
