# Generated by Django 4.1.7 on 2023-02-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0017_alter_person_orcid'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='archived',
            field=models.BooleanField(default=False, help_text='If checked, this resource will not be shown in the registry by default. It will still be accessible if requested.'),
        ),
        migrations.AddField(
            model_name='studydesign',
            name='archived',
            field=models.BooleanField(default=False, help_text='If checked, this study design will not be shown in the registry by default. It will still be accessible if requested.'),
        ),
    ]
