# Generated by Django 4.1.7 on 2023-02-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0018_resource_archived_studydesign_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='kind',
            field=models.CharField(choices=[('MATERIAL', 'Material'), ('TEST_METHOD', 'Test method'), ('PROTOCOL_SOP', 'Protocol or SOP'), ('DATA', 'Data')], max_length=100, verbose_name='Type of resource'),
        ),
    ]
