# Generated by Django 4.1.7 on 2023-03-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0019_alter_resource_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='data_file',
            field=models.FileField(blank=True, help_text='File containing data or information on the resource. In case of multiple files, please upload a zip file.', null=True, upload_to='resources/', verbose_name='Resource file'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='data_link',
            field=models.URLField(blank=True, help_text='Link to the resource (e.g. Zenodo, Figshare, etc.)', null=True, verbose_name='Resource link'),
        ),
    ]
