# Generated by Django 4.2.1 on 2023-05-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0020_alter_resource_data_file_alter_resource_data_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='studydesign',
            name='instance_map_link',
            field=models.URLField(blank=True, help_text='Link to the Instance map', null=True, verbose_name='Instance map link'),
        ),
    ]
