# Generated by Django 4.2.11 on 2024-04-02 09:31

from django.db import migrations, models
import registry.models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0021_studydesign_instance_map_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceCollection',
            fields=[
                ('id', models.CharField(default=registry.models.uuid, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='resource_collections', to='registry.group', verbose_name='Use cases')),
                ('resources', models.ManyToManyField(blank=True, related_name='collections', to='registry.resource')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
