# Generated by Django 4.2.11 on 2024-04-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0023_resource_harmonised_json_resourcefile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resourcestatus',
            options={'ordering': ['position'], 'verbose_name_plural': 'Resource statuses'},
        ),
        migrations.AddField(
            model_name='resourcecollection',
            name='archived',
            field=models.BooleanField(default=False, help_text='If checked, this collection will not be shown in the registry by default. It will still be accessible if requested.'),
        ),
        migrations.AddField(
            model_name='resourcefile',
            name='archived',
            field=models.BooleanField(default=False, help_text='If checked, this file will not be shown in the registry by default. It will still be accessible if requested.'),
        ),
    ]
