# Generated by Django 5.1.4 on 2025-01-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='group',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='license',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='organisation',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='person',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='personrole',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='resource',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='resourcestatus',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='studydesign',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='studydesignnodetag',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='studydesignnodetype',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='license',
            name='sites',
            field=models.ManyToManyField(blank=True, to='sites.site'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='sites',
            field=models.ManyToManyField(blank=True, to='sites.site'),
        ),
        migrations.AlterField(
            model_name='person',
            name='sites',
            field=models.ManyToManyField(blank=True, to='sites.site'),
        ),
    ]
